import 'package:flutter/material.dart';
import 'package:flutterapp/pluzzle_iaapp/generatedloginwidget/generated/GeneratedInputTextWidget3.dart';
import 'package:flutterapp/pluzzle_iaapp/generatedloginwidget/generated/GeneratedButtonPrimaryWidget1.dart';
import 'package:flutterapp/pluzzle_iaapp/generatedloginwidget/generated/GeneratedPageHeaderWidget1.dart';
import 'package:flutterapp/pluzzle_iaapp/generatedloginwidget/generated/GeneratedIOSStatusBarBlackWidget1.dart';
import 'package:flutterapp/pluzzle_iaapp/generatedloginwidget/generated/GeneratedInputTextWidget4.dart';
import 'package:flutterapp/pluzzle_iaapp/generatedloginwidget/generated/GeneratedForgotyourpasswordWidget1.dart';

/* Frame Log In
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLogInWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
          ),
          Positioned(
            left: 16.0,
            top: 60.0,
            right: null,
            bottom: null,
            width: 343.0,
            height: 36.0,
            child: GeneratedPageHeaderWidget1(),
          ),
          Positioned(
            left: 16.0,
            top: 128.0,
            right: null,
            bottom: null,
            width: 343.0,
            height: 50.0,
            child: GeneratedInputTextWidget3(),
          ),
          Positioned(
            left: 16.0,
            top: 194.0,
            right: null,
            bottom: null,
            width: 343.0,
            height: 50.0,
            child: GeneratedInputTextWidget4(),
          ),
          Positioned(
            left: 16.0,
            top: 411.0,
            right: null,
            bottom: null,
            width: 343.0,
            height: 51.0,
            child: GeneratedButtonPrimaryWidget1(),
          )
        ]),
      ),
    ));
  }
}
