import 'package:flutter/material.dart';
import 'package:flutterapp/pluzze_iaapp/generatedturmawidget1/generated/GeneratedEllipse9Widget.dart';
import 'package:flutterapp/pluzze_iaapp/generatedturmawidget1/generated/GeneratedPageHeaderWidget6.dart';
import 'package:flutterapp/pluzze_iaapp/generatedturmawidget1/generated/GeneratedIOSStatusBarBlackWidget6.dart';
import 'package:flutterapp/pluzze_iaapp/generatedturmawidget1/generated/GeneratedEllipse8Widget.dart';
import 'package:flutterapp/pluzze_iaapp/generatedturmawidget1/generated/GeneratedIOSBottomBar5TabsWidget4.dart';
import 'package:flutterapp/pluzze_iaapp/generatedturmawidget1/generated/GeneratedEllipse7Widget.dart';

/* Frame Turma
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTurmaWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget6(),
              ),
              Positioned(
                left: 16.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 36.0,
                child: GeneratedPageHeaderWidget6(),
              ),
              Positioned(
                left: 0.0,
                top: 729.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 83.5,
                child: GeneratedIOSBottomBar5TabsWidget4(),
              ),
              Positioned(
                left: 155.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 16.0,
                child: GeneratedEllipse7Widget(),
              ),
              Positioned(
                left: 178.0,
                top: 390.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedEllipse8Widget(),
              ),
              Positioned(
                left: 200.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 17.0,
                height: 16.0,
                child: GeneratedEllipse9Widget(),
              )
            ]),
      ),
    ));
  }
}
