description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  cupertino_icons: ^1.0.4
  path_drawing: ^1.0.0
  flutter: 
    sdk: "flutter"
  crypto: ^2.0.6
  http: ^0.13.4
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.7.0 <3.0.0"
flutter: 
  assets: 
    - "assets/images/"
  fonts: 
    - 
      family: "Inter"
      fonts: 
        - 
          asset: "fonts/Inter-500.ttf"
          style: "normal"
          weight: 500
        - 
          asset: "fonts/Inter-regular.ttf"
          style: "normal"
          weight: 400
  uses-material-design: true
