import 'package:flutter/material.dart';
import 'package:flutterapp/pluzzle_iaapp/generatedloadingturmawidget/generated/GeneratedIOSStatusBarBlackWidget6.dart';
import 'package:flutterapp/pluzzle_iaapp/generatedloadingturmawidget/generated/GeneratedPageHeaderWidget6.dart';

/* Frame Loading Turma
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoadingTurmaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget6(),
              ),
              Positioned(
                left: 16.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 36.0,
                child: GeneratedPageHeaderWidget6(),
              )
            ]),
      ),
    ));
  }
}
