import 'package:flutter/material.dart';
import 'package:flutterapp/pluzzle_iaapp/generatedpaginainicialdosformswidget/generated/GeneratedContentContentBlockSmallWidget4.dart';
import 'package:flutterapp/pluzzle_iaapp/generatedpaginainicialdosformswidget/generated/GeneratedContentContentBlockSmallWidget5.dart';
import 'package:flutterapp/pluzzle_iaapp/generatedpaginainicialdosformswidget/generated/GeneratedRectangle239Widget.dart';
import 'package:flutterapp/pluzzle_iaapp/generatedpaginainicialdosformswidget/generated/GeneratedNameBioWidget.dart';
import 'package:flutterapp/pluzzle_iaapp/generatedpaginainicialdosformswidget/generated/GeneratedContentContentBlockSmallWidget2.dart';
import 'package:flutterapp/pluzzle_iaapp/generatedpaginainicialdosformswidget/generated/GeneratedPageHeaderWidget2.dart';
import 'package:flutterapp/pluzzle_iaapp/generatedpaginainicialdosformswidget/generated/GeneratedContentContentBlockSmallWidget1.dart';
import 'package:flutterapp/pluzzle_iaapp/generatedpaginainicialdosformswidget/generated/GeneratedSend2Widget.dart';
import 'package:flutterapp/pluzzle_iaapp/generatedpaginainicialdosformswidget/generated/GeneratedSend3Widget.dart';
import 'package:flutterapp/pluzzle_iaapp/generatedpaginainicialdosformswidget/generated/GeneratedSegmentedControlRightWidget.dart';
import 'package:flutterapp/pluzzle_iaapp/generatedpaginainicialdosformswidget/generated/GeneratedContentContentBlockSmallWidget.dart';
import 'package:flutterapp/pluzzle_iaapp/generatedpaginainicialdosformswidget/generated/GeneratedIOSStatusBarWhiteWidget.dart';
import 'package:flutterapp/pluzzle_iaapp/generatedpaginainicialdosformswidget/generated/GeneratedContentContentBlockSmallWidget3.dart';
import 'package:flutterapp/pluzzle_iaapp/generatedpaginainicialdosformswidget/generated/GeneratedSend1Widget.dart';

/* Frame Pagina inicial dos forms
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPaginainicialdosformsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              color: Color.fromARGB(255, 255, 255, 255),
            ),
          ),
          Positioned(
            left: -1.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 376.0,
            height: 130.0,
            child: GeneratedRectangle239Widget(), // cabecalho roxo
          ),
          Positioned(
            left: 16.0,
            top: 60.0,
            right: null,
            bottom: null,
            width: 343.0,
            height: 36.0,
            child: GeneratedPageHeaderWidget2(), // titulo
          ),
          Positioned(
            left: 70.0,
            top: 146.0,
            right: null,
            bottom: null,
            width: 222.0,
            height: 63.0,
            child: GeneratedNameBioWidget(), //nome e curso
          ),
          Positioned(
            left: 13.0,
            top: 225.0,
            right: null,
            bottom: null,
            width: 343.0,
            height: 50.0,
            child:
                GeneratedSegmentedControlRightWidget(), // botoes turma e form
          ),
          Positioned(
            left: 16.0,
            top: 291.0,
            right: null,
            bottom: null,
            width: 343.0,
            height: 77.0000228881836,
            child: GeneratedContentContentBlockSmallWidget3(), // text
          ),
          Positioned(
            left: 32.0,
            top: 306.0,
            right: null,
            bottom: null,
            width: 18.0,
            height: 20.0,
            child: GeneratedSend1Widget(), // send
          ),
        ]),
      ),
    ));
  }
}
