import 'package:flutter/material.dart';
import 'package:flutterapp/pluzzle_iaapp/generatedpaginainicialdasturmaswidget/generated/GeneratedNameBioWidget2.dart';
import 'package:flutterapp/pluzzle_iaapp/generatedpaginainicialdasturmaswidget/generated/GeneratedContentContentBlockSmallWidget12.dart';
import 'package:flutterapp/pluzzle_iaapp/generatedpaginainicialdasturmaswidget/generated/GeneratedSegmentedControlLeftWidget.dart';
import 'package:flutterapp/pluzzle_iaapp/generatedpaginainicialdasturmaswidget/generated/GeneratedPageHeaderWidget4.dart';
import 'package:flutterapp/pluzzle_iaapp/generatedpaginainicialdasturmaswidget/generated/GeneratedContentContentBlockSmallWidget13.dart';
import 'package:flutterapp/pluzzle_iaapp/generatedpaginainicialdasturmaswidget/generated/GeneratedRectangle239Widget2.dart';
import 'package:flutterapp/pluzzle_iaapp/generatedpaginainicialdasturmaswidget/generated/GeneratedIOSStatusBarWhiteWidget2.dart';
import 'package:flutterapp/pluzzle_iaapp/generatedpaginainicialdasturmaswidget/generated/GeneratedContentContentBlockSmallWidget14.dart';

/* Frame Pagina inicial das turmas
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPaginainicialdasturmasWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 130.0,
                child: GeneratedRectangle239Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedIOSStatusBarWhiteWidget2(),
              ),
              Positioned(
                left: 16.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 36.0,
                child: GeneratedPageHeaderWidget4(),
              ),
              Positioned(
                left: 70.0,
                top: 146.0,
                right: null,
                bottom: null,
                width: 222.0,
                height: 63.0,
                child: GeneratedNameBioWidget2(),
              ),
              Positioned(
                left: 16.0,
                top: 291.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 77.0000228881836,
                child: GeneratedContentContentBlockSmallWidget12(),
              ),
              Positioned(
                left: 16.0,
                top: 384.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 77.0000228881836,
                child: GeneratedContentContentBlockSmallWidget13(),
              ),
              Positioned(
                left: 16.0,
                top: 477.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 77.0000228881836,
                child: GeneratedContentContentBlockSmallWidget14(),
              ),
              Positioned(
                left: 13.0,
                top: 225.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 50.0,
                child: GeneratedSegmentedControlLeftWidget(),
              )
            ]),
      ),
    ));
  }
}
