import 'package:flutter/material.dart';
import 'package:flutterapp/pluzze_iaapp/generatedpaginainicialdosformswidget1/generated/GeneratedSend3Widget1.dart';
import 'package:flutterapp/pluzze_iaapp/generatedpaginainicialdosformswidget1/generated/GeneratedContentContentBlockSmallWidget8.dart';
import 'package:flutterapp/pluzze_iaapp/generatedpaginainicialdosformswidget1/generated/GeneratedRectangle239Widget1.dart';
import 'package:flutterapp/pluzze_iaapp/generatedpaginainicialdosformswidget1/generated/GeneratedIOSStatusBarWhiteWidget1.dart';
import 'package:flutterapp/pluzze_iaapp/generatedpaginainicialdosformswidget1/generated/GeneratedContentContentBlockSmallWidget7.dart';
import 'package:flutterapp/pluzze_iaapp/generatedpaginainicialdosformswidget1/generated/GeneratedContentContentBlockSmallWidget9.dart';
import 'package:flutterapp/pluzze_iaapp/generatedpaginainicialdosformswidget1/generated/GeneratedSegmentedControlRightWidget1.dart';
import 'package:flutterapp/pluzze_iaapp/generatedpaginainicialdosformswidget1/generated/GeneratedIOSBottomBar5TabsWidget1.dart';
import 'package:flutterapp/pluzze_iaapp/generatedpaginainicialdosformswidget1/generated/GeneratedNameBioWidget1.dart';
import 'package:flutterapp/pluzze_iaapp/generatedpaginainicialdosformswidget1/generated/GeneratedContentContentBlockSmallWidget6.dart';
import 'package:flutterapp/pluzze_iaapp/generatedpaginainicialdosformswidget1/generated/GeneratedCheckmark2Widget.dart';
import 'package:flutterapp/pluzze_iaapp/generatedpaginainicialdosformswidget1/generated/GeneratedContentContentBlockSmallWidget10.dart';
import 'package:flutterapp/pluzze_iaapp/generatedpaginainicialdosformswidget1/generated/GeneratedPageHeaderWidget3.dart';
import 'package:flutterapp/pluzze_iaapp/generatedpaginainicialdosformswidget1/generated/GeneratedContentContentBlockSmallWidget11.dart';

/* Frame Pagina inicial dos forms
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPaginainicialdosformsWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: -1.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 376.0,
                height: 130.0,
                child: GeneratedRectangle239Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedIOSStatusBarWhiteWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 36.0,
                child: GeneratedPageHeaderWidget3(),
              ),
              Positioned(
                left: 70.0,
                top: 146.0,
                right: null,
                bottom: null,
                width: 222.0,
                height: 63.0,
                child: GeneratedNameBioWidget1(),
              ),
              Positioned(
                left: 13.0,
                top: 225.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 50.0,
                child: GeneratedSegmentedControlRightWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 729.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 83.5,
                child: GeneratedIOSBottomBar5TabsWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 291.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 77.0000228881836,
                child: GeneratedContentContentBlockSmallWidget6(),
              ),
              Positioned(
                left: 16.0,
                top: 384.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 77.0000228881836,
                child: GeneratedContentContentBlockSmallWidget7(),
              ),
              Positioned(
                left: 16.0,
                top: 477.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 77.0000228881836,
                child: GeneratedContentContentBlockSmallWidget8(),
              ),
              Positioned(
                left: 16.0,
                top: 291.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 77.0000228881836,
                child: GeneratedContentContentBlockSmallWidget9(),
              ),
              Positioned(
                left: 16.0,
                top: 384.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 77.0000228881836,
                child: GeneratedContentContentBlockSmallWidget10(),
              ),
              Positioned(
                left: 16.0,
                top: 477.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 77.0000228881836,
                child: GeneratedContentContentBlockSmallWidget11(),
              ),
              Positioned(
                left: 32.0,
                top: 492.0,
                right: null,
                bottom: null,
                width: 18.0,
                height: 20.0,
                child: GeneratedSend3Widget1(),
              ),
              Positioned(
                left: 31.0,
                top: 307.0,
                right: null,
                bottom: null,
                width: 22.0,
                height: 20.0,
                child: GeneratedCheckmark2Widget(),
              )
            ]),
      ),
    ));
  }
}
