import 'package:flutter/material.dart';
import 'package:flutterapp/pluzze_iaapp/generatedturmawidget2/generated/GeneratedIOSBottomBar5TabsWidget5.dart';
import 'package:flutterapp/pluzze_iaapp/generatedturmawidget2/generated/GeneratedPageHeaderWidget7.dart';
import 'package:flutterapp/pluzze_iaapp/generatedturmawidget2/generated/GeneratedIOSStatusBarBlackWidget7.dart';
import 'package:flutterapp/pluzze_iaapp/generatedturmawidget2/generated/GeneratedDataListWidget1.dart';
import 'package:flutterapp/pluzze_iaapp/generatedturmawidget2/generated/GeneratedButtonPrimaryWidget3.dart';

/* Frame Turma
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTurmaWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget7(),
              ),
              Positioned(
                left: 16.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 36.0,
                child: GeneratedPageHeaderWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 729.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 83.5,
                child: GeneratedIOSBottomBar5TabsWidget5(),
              ),
              Positioned(
                left: 16.0,
                top: 112.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 351.0,
                child: GeneratedDataListWidget1(),
              ),
              Positioned(
                left: 17.0,
                top: 645.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget3(),
              )
            ]),
      ),
    ));
  }
}
