import 'package:flutter/material.dart';

/* Rectangle check-mark 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCheckmark3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 22.0,
      height: 20.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/efe8cd757b19cd787a4a0e0c4bc27eadc62164e2.png",
          color: null,
          fit: BoxFit.cover,
          width: 22.0,
          height: 20.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    ));
  }
}
