import 'package:flutter/material.dart';
import 'package:flutterapp/pluzze_iaapp/generatedformswidget1/generated/GeneratedIOSBottomBar5TabsWidget8.dart';
import 'package:flutterapp/pluzze_iaapp/generatedformswidget1/generated/GeneratedImage2Widget.dart';
import 'package:flutterapp/pluzze_iaapp/generatedformswidget1/generated/GeneratedPageHeaderWidget10.dart';
import 'package:flutterapp/pluzze_iaapp/generatedformswidget1/generated/GeneratedIOSStatusBarBlackWidget10.dart';
import 'package:flutterapp/pluzze_iaapp/generatedformswidget1/generated/GeneratedButtonPrimaryWidget5.dart';

/* Frame Forms
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFormsWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 44.0,
                child: GeneratedIOSStatusBarBlackWidget10(),
              ),
              Positioned(
                left: 16.0,
                top: 60.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 36.0,
                child: GeneratedPageHeaderWidget10(),
              ),
              Positioned(
                left: 0.0,
                top: 729.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 83.5,
                child: GeneratedIOSBottomBar5TabsWidget8(),
              ),
              Positioned(
                left: 16.0,
                top: 662.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 51.0,
                child: GeneratedButtonPrimaryWidget5(),
              ),
              Positioned(
                left: 2.0,
                top: 326.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 80.0,
                child: GeneratedImage2Widget(),
              )
            ]),
      ),
    ));
  }
}
